# We specify the directory for Jekyll so we can use @imports.
markdown:    kramdown

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex

sass:
  sass_dir:          _sass
  style:            :compressed
